name: download-test
on:  
  workflow_dispatch:
jobs:  
  get_asset:
    runs-on: ubuntu-latest
    steps:
      - name: List Releases
        run: gh release list --repo diegodocs/terraform-module-azure-vm 
        env:
          GITHUB_TOKEN: ${{ secrets.PRIVATE_REPO_TOKEN }}

      - name: Fetch asset
        run: gh release download --repo diegodocs/terraform-module-azure-vm 
        env:
          GITHUB_TOKEN: ${{ secrets.PRIVATE_REPO_TOKEN }}

      - name: See what we downloaded
        run: tree
