name: download-test
on:  
  workflow_dispatch:
jobs:  
  get_asset:
    runs-on: ubuntu-latest
    steps:
      - name: List Releases
        run: gh release list --repo diegodocs/terraform-module-azure-vm 
        env:
          GITHUB_TOKEN: ${{ secrets.PRIVATE_REPO_TOKEN }}

      # - name: Fetch asset
      #   run: gh release download --repo diegodocs/terraform-module-azure-vm --pattern 'terraform-module-azure-vm*' 
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.PRIVATE_REPO_TOKEN }}

      - name: Download multiple workflow artifacts  
      #uses: marcofaggian/action-download-multiple-artifacts@v3.0.7
        uses: dawidd6/action-download-artifact@v2
        with:   
          repo: diegodocs/terraform-module-azure-vm     
          workflow: terraform-module-azure-vm-package.yml     
          name: terraform-module-azure-vm-1.0.0.4
          path: ./modules/vm 
          github_token: ${{secrets.PRIVATE_REPO_TOKEN}}

      - name: See what we downloaded
        run: tree
