name: 'StarApp-Infra-Release'
 
on:
  pull_request:
     branches:
     - main
  
  workflow_dispatch:
 
jobs:
  job-release-package:
    name: 'Package Architecture'
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
    runs-on: ubuntu-latest
    environment: build
 
    defaults:
      run:
        shell: bash
 
    steps:
    - uses: actions/checkout@v2
    
    - name: Download multiple workflow artifacts  
      #uses: marcofaggian/action-download-multiple-artifacts@v3.0.7
      uses: dawidd6/action-download-artifact@v2
      with:   
        repo: diegodocs/terraform-module-azure-vm     
        workflow: terraform-module-azure-vm-package.yml     
        name: terraform-module-azure-vm-1.0.0.4
        path: ./modules/vm 
        github_token: ${{secrets.PRIVATE_REPO_TOKEN}} 
        
    - name: Display structure of downloaded files
      run: tree
      working-directory: ./

    - uses: actions/upload-artifact@v3
      with:
        name: terraform-azure-starapp-1.0.0.${{ github.run_number }}
        path: ./


  job-release-dev:
    needs: job-release-package
    name: 'Release DEV'
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
    runs-on: ubuntu-latest
    environment: dev
 
    defaults:
      run:
        shell: bash
 
    steps:

    - uses: actions/download-artifact@v3
      with:       
        path: .

    - name: Display structure of downloaded files
      run: tree
      working-directory: .

    - name: 'Terraform Init'
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 1.2.7
        tf_actions_subcommand: 'init'
        tf_actions_working_dir: "./terraform"
         
    - name: 'Terraform Plan'
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 1.2.7
        tf_actions_subcommand: 'plan'
        tf_actions_working_dir: "./terraform"  

    # - name: Terraform Apply
    #   if: github.ref == 'refs/heads/main'
    #   uses: hashicorp/terraform-github-actions@master
    #   with:
    #     tf_actions_version: 1.2.7
    #     tf_actions_subcommand: 'apply'
    #     tf_actions_working_dir: "./terraform"