name: '5starsApp-Infra-Release'
 
on:
  pull_request:
     branches:
     - main
  
  workflow_dispatch:
 
jobs:
  job-package:
    name: 'Package Infra'
    runs-on: ubuntu-latest    
 
    steps:
    - uses: actions/checkout@v2
    
    - name: Download multiple workflow artifacts        
      uses: dawidd6/action-download-artifact@v2
      with:   
        repo: diegodocs/terraform-module-azure-vm     
        workflow: terraform-module-azure-vm-package.yml     
        name: terraform-module-azure-vm-1.0.0.14
        path: ./modules/vm 
        github_token: ${{secrets.PRIVATE_REPO_TOKEN}} 
        
    - name: Display structure of downloaded files
      run: tree
      working-directory: ./

    - uses: actions/upload-artifact@v3
      with:
        name: terraform-azure-infra-starapp-1.0.0.0
        path: ./


  job-release-dev:
    needs: job-package
    name: 'Release DEV'
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
    runs-on: ubuntu-latest
    environment: dev 
   
    steps:

    - uses: actions/download-artifact@v3
      with:       
        path: ./
        name: terraform-azure-infra-starapp-1.0.0.0

    - name: Display structure of downloaded files
      run: tree
      working-directory: ./

    - name: 'Terraform Init'
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 1.2.7
        tf_actions_subcommand: 'init'
        tf_actions_working_dir: "./terraform"
         
    - name: 'Terraform Plan'
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 1.2.7
        tf_actions_subcommand: 'plan'
        tf_actions_working_dir: "./terraform"  

    - name: Terraform Apply
      if: github.ref == 'refs/heads/main'
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 1.2.7
        tf_actions_subcommand: 'apply'
        tf_actions_working_dir: "./terraform"

  job-destroy-dev:
    needs: job-release-dev
    name: 'Destroy DEV'
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
    runs-on: ubuntu-latest
    environment: dev-destroy 
   
    steps:

    - uses: actions/download-artifact@v3
      with:       
        path: ./
        name: terraform-azure-infra-starapp-1.0.0.0

    - name: Display structure of downloaded files
      run: tree
      working-directory: ./

    - name: 'Terraform Init'
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 1.2.7
        tf_actions_subcommand: 'init'
        tf_actions_working_dir: "./terraform"
    
    - name: Terraform Destroy
      if: github.ref == 'refs/heads/main'
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 1.2.7
        tf_actions_subcommand: 'destroy'
        tf_actions_working_dir: "./terraform"

  job-release-qa:
    needs: job-release-dev
    name: 'Release QA'   
    runs-on: ubuntu-latest
    environment: qa
    steps:
    - name: Release PRD
      run: echo Release QA
      working-directory: ./

  job-release-prd:
    needs: job-release-qa
    name: 'Release PRD'   
    runs-on: ubuntu-latest
    environment: prd 
    steps:
    - name: Release PRD
      run: echo Release PRD
      working-directory: ./