name: 'test'

on:
  workflow_dispatch:


jobs:
  job-1:
    name: 'Job One'
    runs-on: ubuntu-latest   
  
    steps:
    - run: echo 'Hello 1'
  job-2:
    name: 'Job Two'
    runs-on: ubuntu-latest   
  
    steps:
    - run: echo 'Hello 2'
   
  job-3:
    name: 'Job three'
    runs-on: ubuntu-latest 
    steps:
    - name: Generate token
      id: generate_token
      uses: tibdex/github-app-token@v1
      with:
        app_id: ${{ secrets.APP_ID }}
        private_key: ${{ secrets.APP_PRIVATE_KEY }}
    - name: Wait for approval
      uses: trstringer/manual-approval@v1
      with:
        secret: ${{ steps.generate_token.outputs.token }}
        approvers: myteam
        minimum-approvals: 1
    - run: echo 'Hello 3'
        

